### PR TITLE
Upgraded/updated the signature generation from HMAC-SHA1 to HMAC-SHA256

### PR DESCRIPTION
**Pull request by MarkKremer**
Signing with HMAC-SHA1 is deprecated. Updated it with the newer HMAC-SHA256.

### CODE REVIEW

**Comment by MujibAzizi** [comment]
Hi Mark!

Thank you for this pull request.

I suppose you've tested this against the test version of Adyen?

**Comment by MarkKremer** [comment]
Hi,

I use it in one of my own projects. However, I forgot something so I will create another/update this pull request soon.

**Comment by MujibAzizi** [comment]
Cool :)

I will wait for your update before I merge this.

**Comment by MarkKremer** [comment]
I think I'm done.

What I was forgotten was to also upgrade the response signature check to SHA256. The thing is, it worked before I upgraded it and I soon found out that it didn't actually check the signature. It just copied the same variable around and calculated the signature. But it compared the copied variable to a less-copied version of itself and didn't do anything with the by calculated signature. It looked a lot like it did but it didn't.
This should all be fixed now. I upgraded the unit tests to SHA256 and expanded one to also check for the above.

I added my name to the authors. There is something written about not messing with the composer.json file. This isn't meant by that, right?

The project I am using this in isn't completely done yet so there could still be some things I haven't thought about (yet) that should still be implemented/fixed. The package is working with it in it current state though. My project should be done by tuesday if you're having doubts.

Kind regards,

Mark Kremer

**Comment by MarkKremer** [comment]
Yeah, I'm going to implement notifications etc.. So it's going to take some time.

**Comment by MujibAzizi** [comment]
Hi Mark,

Thanks for the effort. 

Adding yourself to the authors is not a problem. I did the same thing when I forked the library. 

In the project where we've used this library we also process notifications. We processed those outside Omnipay. We did this because we needed some extra logic which we did not have the time for to implement it inside this library. 

I see that you've closed the merge request. 

It it an idea to merge this one for now and add the notifications in a seperate update?

**Comment by MarkKremer** [comment]
I think that should be possible.

For the notifications; I'm trying to implement the interfaces in one of the current pull request of the omnipay-common package: https://github.com/thephpleague/omnipay-common/pull/58

Do I have to re-open the pull request for you to merge? I don't want any of my "testing" commits to merge.

**Comment by MujibAzizi** [comment]
Hey Mark,

Good that you are implementing the interface. Nice to see you putting a lot of effort in it. 

Can you create a seperate branch for this pull request? This way everything will stay clean.

**Pull request closed without merging**
